//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Code { get; set; }
        public string Book_name { get; set; }
        public string Author { get; set; }
        public string Available { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> SheldId { get; set; }
        public string Des { get; set; }
    }
   
}
